# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d045959e0b4fc27d3fd11aac5bd719e6ec41fc05af25610b2c569b1d3501448bda1e3b9314ce7e61f6707ab8cad0c6f529cfb601252b7c22314fe01e0a1a0c0a

test:
  secret_key_base: 39d9e60a0d74d98285c1414c9b68109da09e671943b1e306bdfcb7004c8cd9746e206c79b11e73e736a9c366422773bec9c0faee416a86f194c8e4b549b34962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
